### ISSUE TITLE
Buttons Overflow

### ISSUE THREAD

**Issue by priyeshpatel** [zerosignalproductions/Freshness-Pancake-Theme#1]
Great theme overall! I've found one bug on the view project page:

![Screenshot](http://i.imgur.com/Moa2L.png)

**Comment by zerosignalproductions** [comment]
Yeah, that's one of the issues I'm still trying to work out. The problem is that I have no way to differentiate that from any other action-bar on another page. Let me see if I can't find a hack for it.

**Comment by zerosignalproductions** [comment]
Ok, what I did was just put a max-width on the button list and push down the client details a bit. It's not exactly what I want it to look like, but it's at least usable now.
