### ISSUE TITLE
Things break in Pancake 3.6

### ISSUE THREAD

**Issue by JasperH8g** [zerosignalproductions/Freshness-Pancake-Theme#10]
After upgrading to Pancake 3.6, I get the following error (only while Freshness is the admin-theme):

An Error Was Encountered [ 500 ]
Unable to locate the file: login.php

**Comment by therealjustinlong** [comment]
AS of 3.6 it appears that they have added a new folder called "modules" to the third_party/themes/admin/theme_name/view folder. If you copy the modules folder found in the latest default theme you should be able to access your control panel again.

**Comment by JasperH8g** [comment]
After doing this, I get this instead:

An Error Was Encountered [ 500 ]
Unable to locate the file: index.php

**Comment by zerosignalproductions** [comment]
I updated the theme with the newest files a little while ago. Are you using the newest version or an older one?

**Comment by zerosignalproductions** [comment]
I just noticed that I accidentally included the original pancake theme in the last commit. It has now been removed. Please try the newest version and see if it works for you.

**Comment by JasperH8g** [comment]
That did the trick, thanks!
