### ISSUE TITLE
Upcoming Tasks container full width.

### ISSUE THREAD

**Issue by mikemcmullan** [zerosignalproductions/Freshness-Pancake-Theme#2]
Thank you for the pancake theme. Two issues, on the admin home page, the upcoming tasks container is full width when I don't think it's supposed to be. Also, the gear icon in the actions column is slightly overflowing the latest activity container.

![Pancake Screenshot](https://dl.dropbox.com/u/2943560/Screen%20Shot%202012-07-11%20at%206.15.27%20PM.png)

**Comment by zerosignalproductions** [comment]
No problem, that should be a quick fix. I'm sure not everything is showing up on my dashboard so I'm probably missing a few things. What browser/version are you using?

**Comment by mikemcmullan** [comment]
Oh sorry forgot that piece of information. I am using Chrome 20 on OSX Lion.

**Comment by zerosignalproductions** [comment]
Should be fixed now. I can't test on OSX, but I saw what the problem was and it's fixed on Chrome for Win7. Let me know if the problem happens to still persist.
