### ISSUE TITLE
Cant select reusable invoice item

### ISSUE THREAD

**Issue by chriz001** [zerosignalproductions/Freshness-Pancake-Theme#3]
The title of my invoice item pops up, but im unable to make it stay. 

love this theme by the way!

**Comment by zerosignalproductions** [comment]
Can you give me a screenshot and what browser/OS you're on and I'll take a look at it right away.

**Comment by chriz001** [comment]
Im on osx using google chrome. 

http://postimage.org/image/4gg6pfuxb/
http://postimage.org/image/3s7c6hw7j/

When i hover out, it goes back to the text i typed in to search,

**Comment by zerosignalproductions** [comment]
Updated the javascript file that was causing the error. Should be good now.
