### ISSUE TITLE
Invoice Total formatting

### ISSUE THREAD

**Issue by aaronmallen** [zerosignalproductions/Freshness-Pancake-Theme#5]
The total due should stand out more.

**Comment by zerosignalproductions** [comment]
Thanks for the input. I'm working on redoing the front end now. I'm running into a bit of trouble with the PDF creator but other wise I hope to have it out in the next couple of weeks.

**Comment by aaronmallen** [comment]
Awesome I will def send a donation your way soon (hopefully next week). It
won't be much, but I plan to donate more later. Awesome work man.

On Fri, Aug 17, 2012 at 5:37 PM, Justin Myers notifications@github.comwrote:

> Thanks for the input. I'm working on redoing the front end now. I'm
> running into a bit of trouble with the PDF creator but other wise I hope to
> have it out in the next couple of weeks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zerosignalproductions/Freshness-Pancake-Theme/issues/5#issuecomment-7837098.

## 

Aaron M. Allen

**Comment by aaronmallen** [comment]
This can be closed :D
